vector_store:
  provider: qdrant
  config:
    host: 127.0.0.1
    port: 6333
    collection_name: mem0_memory

embedder:
  provider: ollama
  config:
    model: nomic-embed-text:latest
    ollama_base_url: http://127.0.0.1:11434

llm:
  provider: ollama
  config:
    model: dolphin-llama3:latest
    ollama_base_url: http://127.0.0.1:11434
    temperature: 0.1

reranker:
  provider: sentence_transformer
  config:
    model: cross-encoder/ms-marco-MiniLM-L-6-v2
    device: cuda
    max_length: 512
